name = "ab-worker-demo"
main = "dist/worker.js"
compatibility_date = "2022-01-12"
workers_dev = true

[build]
command = "npm install && npm run build"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production]
name = "ab-worker-demo"
vars = { ENVIRONMENT = "staging" }